# -*- coding: utf-8 -*-
"""Hello_name

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmR9V2VdWLb6a6T8vouhWCpyFLMJ6snm
"""

# Запрос имени у пользователя
name = input("Как тебя зовут? ")

# Персональное приветствие
print(f"Привет, {name}! Добро пожаловать в мир AI 🚀")