# -*- coding: utf-8 -*-
"""Hello.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zL8cj-N5kbYWPSgTROiyCrN4-nrMGsmH
"""

# hello.py
print("Hello, AI world!")